version = 1

test_patterns = ["src/tests/**/*.js"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]
  plugins = ["react"]
