on: push
name: Publish stories if changed
jobs:
  checkChangesInDocs:
    if: github.repository	== "bdougie/open-sauced"
    name: Check changes in stories
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check changes in stories
      uses: netlify/actions/diff-includes@ffb5acd488eee1f642442bc18ede41459195b138
      with:
        args: stories
  publish:
    needs: checkChangesInDocs
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish
      uses: netlify/actions/build@645ae7398cf5b912a3fa1eb0b88618301aaa85d0
      env:
        BUILD_DIR: storybook-static
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_SITE_ID: sauced-components
        NETLIFY_CMD: npm run build-storybook
